
-- Price History for Ground Truth Verification
CREATE TABLE IF NOT EXISTS price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market TEXT NOT NULL,
    price NUMERIC NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_price_history_market_ts ON price_history (market, timestamp DESC);

-- Enrich Shadow Signals with Attribution Data
ALTER TABLE shadow_signals
ADD COLUMN entry_price NUMERIC,
ADD COLUMN exit_price NUMERIC,
ADD COLUMN outcome TEXT, -- 'WIN', 'LOSS', 'DRAW'
ADD COLUMN realized_pnl NUMERIC;
