
-- Threshold Versions for Adaptive Tuning Audits
CREATE TABLE IF NOT EXISTS threshold_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version TEXT NOT NULL UNIQUE, -- e.g. "th_v1.0"
    strategy TEXT NOT NULL,       -- e.g. "mean_reversion"
    regime TEXT DEFAULT 'ALL',    -- e.g. "mvrv_0" or "ALL"
    config JSONB NOT NULL,        -- The actual threshold values
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT FALSE -- Simple flag for default active version
);

CREATE INDEX idx_threshold_versions_active ON threshold_versions(is_active) WHERE is_active = TRUE;

-- Seed Initial Default
INSERT INTO threshold_versions (version, strategy, regime, config, is_active)
VALUES (
    'th_v1.0_default', 
    'scalping_v1', 
    'ALL', 
    '{
        "rsi": { "oversold": 30, "overbought": 70 },
        "confidence": {
            "min": 0.6,
            "volatilityPenalty": 0.9,
            "baseMultiplier": 0.8,
            "baseOffset": 0.2,
            "crossMax": 0.95
        },
        "weights": { "momentum": 2 }
    }',
    TRUE
);
